version: "3.8"

services:
  hackstreetboys-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - OPENAI_KEY=${OPENAI_KEY}
    volumes:
      - .:/app
      - /app/node_modules
      - app-tmp:/tmp
    command: yarn dev

volumes:
  app-tmp:
