version: '3.8'

services:
  hackstreetboys-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - OPENAPI_KEY=${OPENAPI_KEY}
    volumes:
      - .:/app
      - /app/node_modules
      - app-tmp:/tmp
    command: npm run dev

volumes:
  app-tmp: