version: '3.8'

services:
  hackstreetboys-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - OPENAPI_KEY=${OPENAPI_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - FORM_RECOGNIZER_KEY=${FORM_RECOGNIZER_KEY}
      - FORM_RECOGNIZER_ENDPOINT=${FORM_RECOGNIZER_ENDPOINT}
    restart: unless-stopped
    volumes:
      - app-tmp:/tmp
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  app-tmp: